### PR TITLE
POTR POTS landing page v.1

### PR DESCRIPTION
**Pull request by Dimoshua**
[DEMO LINK](https://Dimoshua.github.io/Potr_Pots/)

### CODE REVIEW

**Review by Anastasiia-Svintsova — CHANGES_REQUESTED** [review]
- The content shouldn't move when the user hovers over a link. Use transform: translate for it 
image

- There is smth wrong with letters. Check it one more time, please 
image

- Fix styles to match the mock 
image
image

- Add link to Instagram as well 
- This section doesn't look good on Tablet 
image

- There is a redundant space on Tabllet and Mobile between the content and screen edge 
image

- The menu should be full-height 
image

- Fix the number position 
image
image

- The background should look good on all screens 
image
image

**Review by DarkMistyRoom — CHANGES_REQUESTED** [review]
- The `-` button doesn't close the info window. Seems like it should do it

- Avoid overlapping with other buttons when some window is opened
image

- Please check the side indents. They should be the same throughout the page
image

- Remove the horizontal scroll from a mobile screen
image

- Fix the overlapping (mobile)
image

- There is still no Instagram link
image

**Review by loralevitska — CHANGES_REQUESTED** [review]
You did an amazing job! Looks good! Let's do some improvements (check comments)
- add smooth scroll for page, now your navigation teleport user to anchors 
- make sure that all interactive elements have a cursor pointer on hover
- don't move this image 
image
- don't move content on hover effect (use hints from previous mentor review)
https://github.com/mate-academy/Potr_Pots/assets/70009205/3ab44533-95b5-4f38-a92b-2e4e18e8dddb
image
- fix this link 
image

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
Great job.
Needs some improvements.
- you set overflow-y for body. it made scrollbar in the midlle of screen...
 looks like you want to fix horizontal scroll and disable overflow for full page - try instead it to find elements which makes horizontal scroll and fix them styles instead disable overflow.
Screenshot from 2023-09-07 13-13-14
Screenshot from 2023-09-07 13-13-02
Screenshot from 2023-09-07 13-12-37
- close button for menu doesn't much design. it should be in the right bottom.
Screenshot from 2023-09-07 13-14-36
- section doesn't much to design:
design: 
Screenshot from 2023-09-07 13-17-02
demo:
Screenshot from 2023-09-07 13-17-47
- suggest to make custom scrollbar for textarea
https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp
Screenshot from 2023-09-07 13-15-36

**Pull request closed without merging**
