### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by olenitut**
https://olenitut.github.io/Potr_Pots/

### CODE REVIEW

**Review by liliia-livandovskaya — CHANGES_REQUESTED** [review]
Looks awesome! Great job! There are several things to work on:

1. Add hover effects to these bloks
Screenshot 2022-11-09 at 14 52 42
Screenshot 2022-11-09 at 14 53 04

2. Check the links, they should open in the new tab, not in the same one  
Screenshot 2022-11-09 at 14 51 51

**Review by liliia-livandovskaya — CHANGES_REQUESTED** [review]
Pay attention to the previous comments they are not fixed, don't forget to deploy the project and then request the review. If something is not clear you can always ask in fe_chat

**Review by liliia-livandovskaya — APPROVED** [review]
🔥 🔥 🔥 🔥 Great job! 🔥 🔥 🔥 🔥

**Review by OlEzhA0 — CHANGES_REQUESTED** [review]
check your textarea
Screenshot 2023-02-16 at 10 11 04 AM

2. Check this bug with menu
Screenshot 2023-02-16 at 10 13 07 AM

**Pull request closed without merging**
