### PR TITLE
add task solution

### PR DESCRIPTION
**Pull request by KaterynaEV**
- [DEMO LINK](https://KaterynaEV.github.io/Potr_Pots/)

### CODE REVIEW

**Review by maxim2310 — CHANGES_REQUESTED** [review]
Good work, but lets make some improvement 

1. looks like superfluous
image
2. rest looks very good, especially gifs, would be nice to liven slider up  
image

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Awesome work! Almost done: 
Screenshot 2023-11-16 at 14 38 55
Screenshot 2023-11-16 at 14 39 05
Consider fixing validation errors 
Screenshot 2023-11-16 at 14 33 58
The content overlaps the menu on scroll, try to fix it

**Review by etojeDenys — CHANGES_REQUESTED** [review]
1. you need to stretch the photo on mobile
image
image


2. same here
image
image

image

**Review by loralevitska — APPROVED** [review]
Amazing)

**Pull request closed without merging**
